# Generated by Django 3.2 on 2021-04-08 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leader', models.CharField(max_length=50)),
                ('theme', models.CharField(max_length=50)),
                ('prelude_time', models.TimeField()),
                ('sermon', models.CharField(max_length=50)),
                ('announcements', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instrument1', models.CharField(max_length=50)),
                ('instrument2', models.CharField(max_length=50)),
                ('vocalYN', models.BooleanField()),
                ('services', models.ManyToManyField(to='order.Service')),
            ],
        ),
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('book', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
                ('services', models.ManyToManyField(to='order.Service')),
            ],
        ),
    ]
