# Generated by Django 3.1.5 on 2021-04-21 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hymn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('book', models.CharField(max_length=50)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('instrument1', models.CharField(blank=True, max_length=50, null=True)),
                ('instrument2', models.CharField(blank=True, max_length=50, null=True)),
                ('vocalYN', models.BooleanField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(blank=True, max_length=50, null=True)),
                ('leader', models.CharField(blank=True, max_length=50, null=True)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('prelude_time', models.CharField(blank=True, max_length=50, null=True)),
                ('sermon', models.CharField(blank=True, max_length=50, null=True)),
                ('announcements', models.CharField(blank=True, max_length=50, null=True)),
                ('special', models.CharField(blank=True, max_length=50, null=True)),
                ('hymn', models.ManyToManyField(blank=True, to='order.Hymn')),
                ('musician', models.ManyToManyField(blank=True, to='order.Musician')),
            ],
        ),
    ]
