# Generated by Django 3.2 on 2021-04-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hymn',
            name='services',
        ),
        migrations.RemoveField(
            model_name='musician',
            name='services',
        ),
        migrations.AddField(
            model_name='service',
            name='musicians',
            field=models.ManyToManyField(to='order.Hymn'),
        ),
    ]
