# Generated by Django 3.2 on 2021-04-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20210408_1118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrument1',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument2',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
