# Generated by Django 3.2 on 2021-04-08 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_auto_20210408_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='instrument1',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='instrument2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
