# Generated by Django 3.2 on 2021-04-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210408_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='Hymns',
            field=models.ManyToManyField(to='order.Hymn'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='vocalYN',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='announcements',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='leader',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='musicians',
            field=models.ManyToManyField(to='order.Musician'),
        ),
        migrations.AlterField(
            model_name='service',
            name='prelude_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='sermon',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='theme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
