# Generated by Django 3.1.5 on 2021-04-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20210408_1125'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='hymns',
            field=models.ManyToManyField(to='order.Hymn'),
        ),
        migrations.AlterField(
            model_name='hymn',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='musician',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='service',
            name='musicians',
            field=models.ManyToManyField(to='order.Musician'),
        ),
    ]
