# Generated by Django 3.2 on 2021-04-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20210412_1419'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='Hymns',
        ),
        migrations.AddField(
            model_name='service',
            name='hymns',
            field=models.ManyToManyField(blank=True, null=True, to='order.Hymn'),
        ),
        migrations.AlterField(
            model_name='service',
            name='musicians',
            field=models.ManyToManyField(blank=True, null=True, to='order.Musician'),
        ),
    ]
