# Generated by Django 3.2 on 2021-04-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20210412_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
